### ISSUE TITLE
TeamsStatus doesn't get updated on changes in logfile

### ISSUE THREAD

**Issue by binderth** [AntoineGS/TeamsStatusV2#19]
Running the German Version of Teams and added the environment variable:
```
PS C:\Scripts> $Env:TSLANG
de
```
So it should search for german text in the log. And it does - first time its started, but then there's no update after the first one like this:
```
{
  "state": "Nicht im Gespräch",
  "attributes": {
    "friendly_name": "Microsoft Teams Activity",
    "icon": "mdi:phone-off"
  }
}
```
If I either start a meeting or just change my status, there's no more update coming through. Is there a way to debug the entire thing?

**Comment by AntoineGS** [comment]
You can run Get-TeamsStatus.ps1 within Powershell ISE to debug it.
However all the log parsing looks for English strings, the translation is only for what gets published to Home Assistant.

**Comment by binderth** [comment]
Thanks! 

I'd take a look into the specifics of the code, but there's German expressions for the current team status and not English ones. Could it be that there wa a change recently in the way Teams logs Infos?

**Comment by binderth** [comment]
Ok, I managed to run the script in Powershell ISE and from what I see, it's indeed German mixed into the log.txt:

so, `Get-TeamsStatus.ps1` searches for the (english) Hashes in line 87ff, but the line it finds is:
```
Fri Jan 20 2023 09:21:10 GMT+0100 (Mitteleuropäische Normalzeit) <3692> -- info -- Setting the taskbar overlay icon - Beschäftigt 
```
and there's "Beschäftigt" instead of "Busy", which I think causes the script to not find the Teams Status?

**Comment by binderth** [comment]
additional question: what is the trigger to rerun the logfile-check? I'm not used in powerShell, but I get the feeling, that there's no more recurring `Get-Content...` (line 67) after the first run. The script still runs, but there's no more action after the first round from what I can tell in it...

**Comment by AntoineGS** [comment]
Yeah exactly!

If we want to support other languages we would need to extract all of the English strings used in any of the parsing into variables (like we do for the Home Assistant statuses).
From what I quickly counted there would be just under 30 strings to extract.

**Comment by binderth** [comment]
Sorry for the delay - so as I use a german Teams, I just edited lines 35-48 to use the german terms in the "teamStatusHash" and it seems to catch all "TeamStatus" changes as intended.
The others "TeamsActivity" is untouched, as the terms in my german log are also in english for that searches within the Script.

So, I don't know how to do that - sorry, but there's already the "Lang-de.ps1", which does use the same expressions as there are in the $teamsStatusHash. So I think it would be an option to read the current language setting and fill the hash from that file? That way, you can also change the language-file, if you did change the names for the statusses within Teams also?
