### ISSUE TITLE
Powershell starts not hidden in Windows 11

### ISSUE THREAD

**Issue by binderth** [AntoineGS/TeamsStatusV2#26]
I just got upgraded to Windows 11 and since then, the script does not hide, but is active in a powerShell window at all time.
I think it's not really TeamsStatusV2 related, but is there a way to hide it?

looks like here:
![grafik](https://github.com/AntoineGS/TeamsStatusV2/assets/9037329/e65c7c34-b65c-4271-a1a8-a2d69ae29b71)

**Comment by bmdixon** [comment]
This is a Windows Terminal bug - https://github.com/microsoft/terminal/issues/12464.
