### ISSUE TITLE
Invoke-RestMethod : 401: Unauthorized

### ISSUE THREAD

**Issue by jlandgrave62** [AntoineGS/TeamsStatusV2#5]
I didn't get this message with the exact same settings in the older, non-forked version.  I have the long lived token in the Settings.ps1 file.  Is this failing on the token?

Invoke-RestMethod : 401: Unauthorized
At C:\scripts\TSFunctions.ps1:25 char:5
+     Invoke-RestMethod -Uri "https://landgravelake.duckdns.org/api/sta ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by AntoineGS** [comment]
I tried replicating the problem and the only way I was able to is by
inputting an incorrect token.
I have renamed the variables since the non-forked version, is it possible
you are using the old variable names?
I would also recommend using system variables as it will be easier to
update the project if ever you need to.
If that does not work then I will see about sending you the steps to call
the HA API from Postman to take the application out of the equation.

Antoine Gaudreau Simard

**Comment by jlandgrave** [comment]
DOH!!! I copied the settings from the V1 Settings file and didn't notice that you had changed the variables.  Once I configured the variables properly it works.  The other issue I had is that the machine I'm using is a corporate machine and when I log into the machine I have to login with a DomainName\SAMAccount name.  But when you use the environment variable for a user name (to register the webcam piece) it only brings back the SAMAccount name and NOT the domain name.  I created a local user with the same name as my enterprise account but that's not the ideal solution.

**Comment by AntoineGS** [comment]
If I were to create a config for it, would the same value work for both instances of $Username below? 
- `C:\Users\$Username\AppData\Roaming\Microsoft\Teams\logs.txt`
- `HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam\NonPackaged\C:#Users#$Username#AppData#Local#Microsoft#Teams#current#Teams.exe`

If so I'll commit the change and you will be able to create a System Variable to override the Windows' one

**Comment by AntoineGS** [comment]
PS: I committed the change to the development branch if you want to test it out, including the updated doc with the new variable name!

**Comment by jlandgrave62** [comment]
I’ll try it tonight and report back!


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by AntoineGS** [comment]
@jlandgrave did it end up working?
I did merge the changes into the official v1.0.2 release so no need to get the dev branch.

**Comment by jlandgrave62** [comment]
Sorry for my lack of response.  Yes, it worked.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by AntoineGS** [comment]
No worries, just cleaning up open issues, glad to hear it worked!
