### ISSUE TITLE
sensor.teams_status validation message 'contains non-whitespace: None

### ISSUE THREAD

**Issue by mhoogenbosch** [AntoineGS/TeamsStatusV2#7]
My HA logs now say:

`Error validating template result 'None' from template 'Template("{{state_attr('input_text.teams_status','icon')}}")' for attribute '_attr_icon' in entity sensor.teams_status validation message 'contains non-whitespace: None'`

I think it started when I upgraded to 2022.7.5 (moved directly from 2022.6.7 to 2022.7.5).

I can't seem to figure out what is wrong, I have not changed a thing.

**Comment by AntoineGS** [comment]
Are you still getting this error?
I have nothing in my HA logs, it might be a special character somewhere that looks like a space.
Maybe deleting the project, redownloading the files and retyping the configurations would help? 
It's a shot in the dark but seeing that it works fine here it seems to be installation-specific.

**Comment by mhoogenbosch** [comment]
Nope sorry for not closing, no issues.

**Comment by AntoineGS** [comment]
Glad to hear the issue is gone ;)
